// UI indicator
export const UI_IS_LOADING = 'UI_IS_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';

// Cities
export const REQUEST_CITIES = 'REQUEST_CITIES';
export const RECEIVE_CITIES = 'RECEIVE_CITIES';
export const FAIL_GET_CITIES = 'FAIL_GET_CITIES';

// Subjects
export const REQUEST_SUBJECTS = 'REQUEST_SUBJECTS';
export const RECEIVE_SUBJECTS = 'RECEIVE_SUBJECTS';
export const FAIL_GET_SUBJECTS = 'FAIL_GET_SUBJECTS';

// Users
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const FAIL_GET_USER = 'FAIL_GET_USER';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const RECEIVE_SIGN_UP = 'RECEIVE_SIGN_UP';
export const FAIL_SIGN_UP = 'FAIL_GET_SIGN_UP';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const RECEIVE_SIGN_IN = 'RECEIVE_SIGN_IN';
export const FAIL_SIGN_IN = 'FAIL_GET_SIGN_IN';
export const REQUEST_USER_UPDATE = 'REQUEST_USER_UPDATE';
export const RECEIVE_USER_UPDATE = 'RECEIVE_USER_UPDATE';
export const FAIL_USER_UPDATE = 'FAIL_GET_USER_UPDATE';
export const UPDATE_FCM_TOKEN = 'UPDATE_FCM_TOKEN';
export const REQUEST_FCM_ADD = 'REQUEST_FCM_ADD';
export const RECEIVE_FCM_ADD = 'RECEIVE_FCM_ADD';
export const FAIL_FCM_ADD = 'FAIL_GET_FCM_ADD';
export const REQUEST_FCM_UPDATE = 'REQUEST_FCM_UPDATE';
export const RECEIVE_FCM_UPDATE = 'RECEIVE_FCM_UPDATE';
export const FAIL_FCM_UPDATE = 'FAIL_GET_FCM_UPDATE';
export const UPDATE_USER_CITIES = 'UPDATE_USER_CITIES';
export const UPDATE_USER_SUBJECTS = 'UPDATE_USER_SUBJECTS';


// Announces
export const REQUEST_ANNOUNCES = 'REQUEST_ANNOUNCES';
export const RECEIVE_ANNOUNCES = 'RECEIVE_ANNOUNCES';
export const FAIL_GET_ANNOUNCES = 'FAIL_GET_ANNOUNCES';
export const REQUEST_UPD_RELATION = 'REQUEST_UPD_RELATION';
export const RECEIVE_UPD_RELATION = 'RECEIVE_UPD_RELATION';
export const FAIL_UPD_RELATION = 'FAIL_UPD_RELATION';
export const REQUEST_GET_RELATION = 'REQUEST_GET_RELATION';
export const RECEIVE_GET_RELATION = 'RECEIVE_GET_RELATION';
export const FAIL_GET_RELATION = 'FAIL_GET_RELATION';
export const REQUEST_BILL = 'REQUEST_BILL';
export const RECEIVE_BILL = 'RECEIVE_BILL';
export const FAIL_BILL = 'FAIL_BILL';

// News
export const REQUEST_NEWS = 'REQUEST_NEWS';
export const RECEIVE_NEWS = 'RECEIVE_NEWS';
export const FAIL_GET_NEWS = 'FAIL_GET_NEWS';

// Menu
export const REQUEST_MENU = 'REQUEST_MENU';
export const RECEIVE_MENU = 'RECEIVE_MENU';
export const FAIL_GET_MENU = 'FAIL_GET_MENU';

// FEEDBACK
export const REQUEST_FEEDBACK = 'REQUEST_FEEDBACK';
export const RECEIVE_FEEDBACK = 'RECEIVE_FEEDBACK';
export const FAIL_GET_FEEDBACK = 'FAIL_GET_FEEDBACK';

// Main slider
export const REQUEST_SLIDES = 'REQUEST_SLIDES';
export const RECEIVE_SLIDES = 'RECEIVE_SLIDES';
export const FAIL_GET_SLIDES = 'FAIL_GET_SLIDES';

// Debug
export const DEBUG_INCREMENT = 'DEBUG_INCREMENT';