// UI indicator
export const UI_IS_LOADING = 'UI_IS_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';

// Cities
export const REQUEST_CITIES = 'REQUEST_CITIES';
export const RECEIVE_CITIES = 'RECEIVE_CITIES';
export const FAIL_GET_CITIES = 'FAIL_GET_CITIES';

// Subjects
export const REQUEST_SUBJECTS = 'REQUEST_SUBJECTS';
export const RECEIVE_SUBJECTS = 'RECEIVE_SUBJECTS';
export const FAIL_GET_SUBJECTS = 'FAIL_GET_SUBJECTS';

// Users
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const FAIL_GET_USER = 'FAIL_GET_USER';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const RECEIVE_SIGN_UP = 'RECEIVE_SIGN_UP';
export const FAIL_SIGN_UP = 'FAIL_GET_SIGN_UP';
export const REQUEST_USER_UPDATE = 'REQUEST_USER_UPDATE';
export const RECEIVE_USER_UPDATE = 'RECEIVE_USER_UPDATE';
export const FAIL_USER_UPDATE = 'FAIL_GET_USER_UPDATE';

// Announces
export const SET_CURRENT_ANNOUNCE = 'SET_CURRENT_ANNOUNCE';
export const REQUEST_ANNOUNCES = 'REQUEST_ANNOUNCES';
export const RECEIVE_ANNOUNCES = 'RECEIVE_ANNOUNCES';
export const FAIL_GET_ANNOUNCES = 'FAIL_GET_ANNOUNCES';

// News
export const SET_CURRENT_NEWS_POST = 'SET_CURRENT_NEWS_POST';

// Debug
export const DEBUG_INCREMENT = 'DEBUG_INCREMENT';