# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'seminarPro' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for seminarPro
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'

  target 'seminarProTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'seminarPro-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for seminarPro-tvOS

  target 'seminarPro-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
